### ISSUE TITLE
other thermostats

### ISSUE THREAD

**Issue by feeleep75** [Hernas/homebridge-salus-sq610#2]
Hi - is there a reason you did not include other Salus devices like: https://salus-controls.eu/product-card/vs20wrf-wireless-digital-thermostat

It seems to be working when I add new model but maybe there is a deeper reason...

**Comment by bimusiek** [comment]
It just that I did not have it tested. And in other open source Salis implementations it was filtered out. 

Please open the PR and I will update the code.

**Comment by feeleep75** [comment]
OK - I will test if it works properly and submit the change

**Comment by bimusiek** [comment]
Fixed in v1.1.0
