### ISSUE TITLE
New Salus AWS plattform

### ISSUE THREAD

**Issue by california444** [Hernas/homebridge-salus-sq610#5]
Hi @bimusiek,
do you now if it is save to switch to new Salus AWS Plattform? 
Have you migrated already? Does the plugin still work?

thanks!

**Comment by bimusiek** [comment]
I have heard from one user about it and tried to quickly fix it but did not have time yet. This looks similar to Panasonic Comfort Cloud issue, so please be patient.

**Comment by california444** [comment]
So it is more than changing the URL in the config?

**Comment by bimusiek** [comment]
Unfortunately yes, Salus changed how the auth works. You can already change the url in config because I thought that would be enough.

**Comment by california444** [comment]
looks like they are now using AWS Cognito.
I can see a AWSCognitoIdentityProviderService.InitiateAuth (with "AuthFlow":"USER_SRP_AUTH"), followed by a AWSCognitoIdentityProviderService.RespondToAuthChallenge and a AWSCognitoIdentityService.GetCredentialsForIdentity

**Comment by pettersandholt** [comment]
Any update on this? Would be amazing to get it working again :)

**Comment by mjrybarski** [comment]
still no updates?

**Comment by bimusiek** [comment]
Unfortunately due to other issues with homebridge I have switched to HomeAssistant. It has much better support for smart homes configurations and it has already existing Salus plugin that works locally. 

I could take a look at their sourcecode and implement the same for this plugin but I don't have the time as of now.

**Comment by RockstarRebell** [comment]
Hi Bimusiek, it would be great if you could if you could fix it! Thanx a lot! Greetings

**Comment by PuscasAdi** [comment]
> Unfortunately due to other issues with homebridge I have switched to HomeAssistant. It has much better support for smart homes configurations and it has already existing Salus plugin that works locally. 
> 
> 
> 
> I could take a look at their sourcecode and implement the same for this plugin but I don't have the time as of now.

Can you please attach the link to the HomeAsssistant SALUS plugin?

**Comment by bimusiek** [comment]
https://github.com/epoplavskis/homeassistant_salus
I am using this one.

**Comment by Moater11** [comment]
Hi there. Any chance we can get this plugin working again via Hoobs? Many thanks.

**Comment by california444** [comment]
HI, 
I was curious to understand why and how the home assistant plugin works with the new platform...
The difference to this plugin is, that they do not use the cloud platform at all, but make requests to the UGW in the local network.
I then spent a lot of time to figure out how to port the encryption algorithm from pyhton to Javascript. I finally managed to make the encrypted API calls  retrieve data from UGW directly for my thermostats. The data structure seems a bit different (but not too different...).
Yesterday evening I started to port my quick and dirty JS code into Typescript and to integrate it into the structure of this plugin.

@bimusiek are you open for a PR changing from cloud platform with user and password to local connection with ip address and EU-ID of the UGW? 
It is still work in progress on my side and I am quite busy with other things. But I hope to be able to make a initial suggestion in the next days if everything's works as I expect...

**Comment by california444** [comment]
fyi
https://github.com/california444/homebridge-salus-sq610

There is a draft version, which is "working":
- I can get all my 10x SQ610RF thermostats
- it reads the temperature and state
- updating is working
- I can set a least the temperature and it updates in the Salus app

Might still be a bit buggy und not very well tested....

**Comment by RockstarRebell** [comment]
Hallo california444, thanks so much for your work! I tried for 3 hours with help from chatgpt but i'm nor able to install the draft version correctly. It doesn't work.  
"No plugin was found for the platform "SalusSQ610HomebridgePlugin" in your config.json. Please make sure the corresponding plugin is installed correctly."

pi@homebridge:/var/lib/homebridge $ /opt/homebridge/bin/npm uninstall -g @hernas/homebridge-salus-sq610

removed 1 package in 2s
pi@homebridge:/var/lib/homebridge $ /opt/homebridge/bin/npm cache clean --force
pi@homebridge:/var/lib/homebridge $ /opt/homebridge/bin/npm install -g california444/homebridge-salus-sq610

added 16 packages in 18s
pi@homebridge:/var/lib/homebridge $ /opt/homebridge/bin/npm list -g --depth=0
/opt/homebridge/lib
├── @hernas/homebridge-salus-sq610@
├── corepack@0.29.3
├── homebridge-config-ui-x@4.62.0
└── npm@10.8.2

ChatGPT said that a version-number is missing.

**Comment by california444** [comment]
HI @RockstarRebell ,
yeah, I am not an expert with npm, but I get the same issue when I repeat your steps and try to install it directly from Github.
So I pushed the current version to npm. You should now be able to search within homebridge UI:

<img width="337" alt="image" src="https://github.com/user-attachments/assets/7d5fcb30-4741-499d-9934-5abb910596be">

Also you  need to change your config and add the ip address of your local Gateways and you either can they with eu_id: 0000000000000000 or if this does not work, check the eu_id mentioned on the bottom side of the gateway

`        {
            "ip_address": "192.168.0.88",
            "eu_id": "0000000000000000",
            "refreshTime": 60,
            "platform": "SalusSQ610HomebridgePlugin"
            }`

**Comment by bimusiek** [comment]
@california444 if you create the PR, I am happy to merge  and test it.

**Comment by RockstarRebell** [comment]
It works! 🤩 thank you so much!

**Comment by california444** [comment]
Glad that it works…
I will try to create the PR soon here…

**Comment by california444** [comment]
here we go: https://github.com/Hernas/homebridge-salus-sq610/pull/7
