### ISSUE TITLE
Can't add any device to HB.  I'm getting a request failed with 404 error.

### ISSUE THREAD

**Issue by leoburnettbucharest** [Hernas/homebridge-salus-sq610#6]
**Describe The Bug:**
Hi!  I'm trying to add my devices to HB but I can't.  I have a UGE600 gateway and VS20WRF thermostats.  The error, below, in the <em>logs</em> section.

Please note that I do not connect to eu.salusconnect.io but to eu.premium.salusconnect.io.  

I haven't been able to make it work.  Today upgraded HB to 1.8.5 but the problem persists.

Is it anything else I should do in my Salus account to make it work?

Thank you!

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
[10/28/2024, 4:55:21 PM] [@hernas/homebridge-salus-sq610] Could not load the devices: Error: Request failed with status code 404
```

**Plugin Config:**

```json
{
    "email": "xxxx",
    "password": "xxxx",
    "salusUrl": "eu.premium.salusconnect.io",
    "refreshTime": 15,
    "_bridge": {
        "username": "0E:8F:B8:45:55:3B",
        "port": 32611
    },
    "platform": "SalusSQ610HomebridgePlugin"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.1.1
* **Homebridge Version**: 1.8.4 (just upgraded to 1.8.5)
* **Node.js Version**: 20.9.0
* **NPM Version**: 10.8.2
* **Operating System**: Synology DSM

**Comment by Moater11** [comment]
Same problem via Hoobs. it appears the old API connection method to Salus was changed and now a plugin update is required to connect to Salus gateway account. Hope someone will look into this. Thanks

**Comment by leoburnettbucharest** [comment]
@bimusiek , excellent!  Thank you!
